import os
def find_prj_root(path=os.getcwd()):
    if os.path.isfile(os.path.join(path,".PRJ_ROOT")):
        return path
    else:
        if path:
            return find_prj_root(os.path.dirname(path))
        else:
            raise Exception("Can not find the PRJ_ROOT directory")

PRJ_ROOT=find_prj_root()
ROOT = os.path.dirname(PRJ_ROOT)
SRC_DIR=PRJ_ROOT+'/local/src'
BIN_DIR=PRJ_ROOT+'/local/bin'
SHR_DIR=PRJ_ROOT+'/local/bin'
DATASET_DIR=PRJ_ROOT+'/dataset'
PLH_DIR=DATASET_DIR+"/snake_workflow"


GENOME="GrCh38"
BINNING="variable_500000_101_bwa"

REF=SHR_DIR+"/data/genome.fa"
GINKGO_BINS=SHR_DIR+"/data/ginkgo_variable_500000_bins.bed"

WGSIM=SRC_DIR+"/cnsc_simulator"

SIMULATOR=BIN_DIR+"main.par"
MAKE_GT=BIN_DIR+"read_tree"
SPLIT_GT=BIN_DIR+"/sep_ground_truth.py"
BIN_GT=BIN_DIR+"/make_ginkgo_beds.py"
MK_SEGCOPY=BIN_DIR+"/make_segcopy.py"
HEATMAP=BIN_DIR+"/heatmap.py"
MK_NEWICK=BIN_DIR+"/weighted_dot_to_newick.py"
MK_DIST_MATRIX=BIN_DIR+"/newick_to_mat.py"
MK_DOT=BIN_DIR+"/mk_dot.py"
PREPROC=BIN_DIR+"/preproc.py"
PREPROC_UMAP=BIN_DIR+"/preproc_umap.py"
COPH_AFFINITY_SCORE=BIN_DIR+"/cophenetic_affinity.py"
MERGE_METRICS=BIN_DIR+"/merge_clustering_stats.py"
COPH_STATS=BIN_DIR+"/coph_aff_stats.py"
TIME_STATS=BIN_DIR+"/time_stats.py"
SILHOUETTE_STATS=BIN_DIR+"/silhouette_stats.py"
CONNECTIVITY_STATS=BIN_DIR+"/connectivity_stats.py"
DUNN_STATS=BIN_DIR+"/dunn_stats.py"
DBCV_STATS=BIN_DIR+"/density_valid_stats.py"
APN_STATS=BIN_DIR+"/apn_stats.py"
STABILITY=BIN_DIR+"/cl_stability.py"
INT_VALIDATION=BIN_DIR+"/cl_validity.py"
NWK_HEATMAP=BIN_DIR+"/plot_newick_heatmap.py"
MK_CLUSTERS_HEATMAP=BIN_DIR+"/cluster_heatmap.py"
MK_CLUSTERS_HEATMAP_AGGL=BIN_DIR+"/plot_aggl_heatmap.py"
TREE_CLUSTER=BIN_DIR+"/TreeCluster.py"
EXT_VALIDATION=BIN_DIR+"/cl_external_validation.py"
PLT_GT_CLUSTERS=BIN_DIR+"/plot_newick_clusters.py"



TOOLS = {
    'affinity': BIN_DIR+'/affinity.py',
    'agglomerative': BIN_DIR+'/agglomerative.py',
    'birch': BIN_DIR+'/birch.py',
    'kmeans': BIN_DIR+'/kmeans.py',
    'hdbscan':BIN_DIR+'/hdbscan_.py',
    'dbscan':BIN_DIR+'/dbscan.py',

}

TOOLS_ = {
    'affinity': SRC_DIR+'/affinity.py',
    'birch': SRC_DIR+'/birch.py',
    'kmeans': SRC_DIR+'/kmeans.py',
    'hdbscan':SRC_DIR+'/hdbscan_.py',
    'dbscan':SRC_DIR+'/dbscan.py',

}
LINKAGE=["ward", "complete", "average", "single"]

CLUSTERINGS=["affinity", "agglomerative_average", "agglomerative_complete", 
            "agglomerative_single", "agglomerative_ward", "birch", 
            "dbscan",  "hdbscan", "kmeans"]
CLUSTERINGS_STR = "affinity agglomerative_average agglomerative_complete agglomerative_single agglomerative_ward birch dbscan hdbscan kmeans"

EXP = {
    "Exp100" : {
        "n" : 100
    },
    "Exp200" : {
        "n" : 200
    },
    "Exp400" : {
        "n" : 400
    }

}

SAMPLES=["Sample1", "Sample2", "Sample3", "Sample4", "Sample5",
        "Sample6", "Sample7", "Sample8", "Sample9", "Sample10",
        "Sample11", "Sample12", "Sample13", "Sample14", "Sample15",
        "Sample16", "Sample17", "Sample18", "Sample19", "Sample20",
        "Sample21", "Sample22", "Sample23", "Sample24", "Sample25",
        "Sample26", "Sample27", "Sample28", "Sample29", "Sample30",
        "Sample31", "Sample32", "Sample33", "Sample34", "Sample35",
        "Sample36", "Sample37", "Sample38", "Sample39", "Sample40",
        "Sample41", "Sample42", "Sample43", "Sample44", "Sample45",
        "Sample46", "Sample47", "Sample48", "Sample49", "Sample50",
        ] 